# Generated by Django 5.2.8 on 2026-01-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_forgotpasswordrequest_alter_userprofile_team_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicLeagueModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leauge_name", models.CharField(max_length=100)),
                (
                    "leauge_description",
                    models.TextField(blank=True, max_length=150, null=True),
                ),
                (
                    "leauge_logo",
                    models.CharField(
                        choices=[
                            ("paris_fc", "Paris FC"),
                            ("lakers", "Lakers"),
                            ("boston_celtics", "Boston Celtics"),
                            ("chicago_bulls", "Chicago Bulls"),
                            ("atlanta_hawks", "Atlanta Hawks"),
                            ("golden_state_warriors", "Golden State Warriors"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "team_budget",
                    models.CharField(
                        choices=[("50M", "50 Million"), ("100M", "100 Million")],
                        default="100M",
                        max_length=10,
                    ),
                ),
                (
                    "max_team_number",
                    models.CharField(
                        choices=[("4", "4"), ("6", "6"), ("8", "8"), ("10", "10")],
                        default="10",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("is_ready", models.BooleanField(default=False)),
                ("is_started", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_public_leagues",
                        to="users.userprofile",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_public_leagues",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creator", "leauge_name"),
                        name="unique_user_public_league_name",
                    )
                ],
            },
        ),
    ]
