# Generated by Django 5.2.8 on 2026-01-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateleaguemodel',
            name='leauge_logo',
            field=models.CharField(choices=[('paris_fc', 'Paris FC'), ('lakers', 'Lakers'), ('boston_celtics', 'Boston Celtics'), ('chicago_bulls', 'Chicago Bulls'), ('atlanta_hawks', 'Atlanta Hawks'), ('golden_state_warriors', 'Golden State Warriors')], max_length=200),
        ),
    ]
