# Generated by Django 5.2.8 on 2026-01-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "matches",
            "0005_publicleagueseason_publicmatchmodel_publicmatchpair_and_more",
        ),
        ("players", "0001_initial"),
        ("users", "0002_forgotpasswordrequest_alter_userprofile_team_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicTeamSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_players", models.JSONField(default=list)),
                ("total_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_selections",
                        to="matches.publicmatchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_selections",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("match", "owner")},
            },
        ),
    ]
