# Generated by Django 5.2.8 on 2026-01-09 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("otp_created_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_logo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paris_fc", "Paris FC"),
                            ("lakers", "Lakers"),
                            ("boston_celtics", "Boston Celtics"),
                            ("chicago_bulls", "Chicago Bulls"),
                            ("atlanta_hawks", "Atlanta Hawks"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("team_name", models.CharField(max_length=100, unique=True)),
                (
                    "favorite_team",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("accept_terms_conditions", models.BooleanField(default=False)),
                ("recived_notifications", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
