# Generated by Django 5.2.8 on 2026-01-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team_logo',
            field=models.CharField(blank=True, choices=[('paris_fc', 'Paris FC'), ('lakers', 'Lakers'), ('boston_celtics', 'Boston Celtics'), ('chicago_bulls', 'Chicago Bulls'), ('atlanta_hawks', 'Atlanta Hawks'), ('golden_state_warriors', 'Golden State Warriors')], max_length=100, null=True),
        ),
    ]
