# Generated by Django 5.2.8 on 2026-01-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStatsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_played", models.IntegerField(default=0)),
                ("trophies", models.JSONField(blank=True, default=list, null=True)),
                (
                    "average_point_scored",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "average_point_conceded",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("league_played", models.IntegerField(default=0)),
                ("league_won", models.IntegerField(default=0)),
                ("league_loss", models.IntegerField(default=0)),
                ("no_battle", models.IntegerField(default=0)),
                ("regular_season_won", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MyTeamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_list", models.JSONField(blank=True, default=list, null=True)),
                (
                    "player_position",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("player_price", models.FloatField(blank=True, default=0.0, null=True)),
                ("leauge_id", models.CharField(blank=True, max_length=100, null=True)),
                ("match_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "team_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_teams",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
