# Generated by Django 5.2.8 on 2026-01-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("private_leagues", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nba_season", models.CharField(max_length=20)),
                ("regular_season_start", models.DateTimeField()),
                ("regular_season_end", models.DateTimeField()),
                ("playoff_start", models.DateTimeField()),
                ("playoff_end", models.DateTimeField()),
                ("current_match_day", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season",
                        to="private_leagues.privateleaguemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_day", models.IntegerField()),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("regular_season", "Regular Season"),
                            ("playoffs", "Playoffs"),
                        ],
                        default="regular_season",
                        max_length=20,
                    ),
                ),
                ("match_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="private_leagues.privateleaguemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_date"],
            },
        ),
        migrations.CreateModel(
            name="MatchPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_a", models.IntegerField(default=0)),
                ("score_b", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="matches.matchmodel",
                    ),
                ),
                (
                    "player_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_as_a",
                        to="users.userprofile",
                    ),
                ),
                (
                    "player_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_as_b",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchScoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_scored", models.IntegerField(default=0)),
                ("bonus_points", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_scores",
                        to="matches.matchmodel",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_points"],
            },
        ),
        migrations.CreateModel(
            name="PlayoffQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regular_season_rank", models.IntegerField()),
                ("total_points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playoff_qualifications",
                        to="private_leagues.privateleaguemodel",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["regular_season_rank"],
            },
        ),
        migrations.AddIndex(
            model_name="matchmodel",
            index=models.Index(
                fields=["league", "match_type"], name="matches_mat_league__0be0e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchmodel",
            index=models.Index(
                fields=["league", "status"], name="matches_mat_league__e7b70c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchpair",
            index=models.Index(
                fields=["match", "player_a"], name="matches_mat_match_i_fadc08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchpair",
            index=models.Index(
                fields=["match", "player_b"], name="matches_mat_match_i_3a13a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchscoremodel",
            unique_together={("match", "player")},
        ),
        migrations.AlterUniqueTogether(
            name="playoffqualification",
            unique_together={("league", "player")},
        ),
    ]
