# Generated by Django 5.2.8 on 2026-01-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchLineupModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("players", models.JSONField(default=list)),
                ("total_score", models.FloatField(default=0.0)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="matches.matchmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_lineups",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["match", "user"], name="matches_mat_match_i_1bca9f_idx"
                    )
                ],
                "unique_together": {("match", "user")},
            },
        ),
    ]
