# Generated by Django 5.2.8 on 2026-01-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_matchlineupmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MatchLineupModel",
        ),
    ]
