# Generated by Django 5.2.8 on 2026-01-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private_leagues", "0002_alter_privateleaguemodel_leauge_logo"),
        ("matches", "0003_delete_matchlineupmodel"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="matchmodel",
            name="matches_mat_league__0be0e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="matchmodel",
            name="matches_mat_league__e7b70c_idx",
        ),
        migrations.RenameField(
            model_name="matchmodel",
            old_name="league",
            new_name="league_id",
        ),
        migrations.AddIndex(
            model_name="matchmodel",
            index=models.Index(
                fields=["league_id", "match_type"],
                name="matches_mat_league__a6d240_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchmodel",
            index=models.Index(
                fields=["league_id", "status"], name="matches_mat_league__946c1d_idx"
            ),
        ),
    ]
