# Generated by Django 5.2.8 on 2026-01-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_remove_matchmodel_matches_mat_league__0be0e6_idx_and_more"),
        ("public_leagues", "0001_initial"),
        ("users", "0002_forgotpasswordrequest_alter_userprofile_team_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicLeagueSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nba_season", models.CharField(max_length=20)),
                ("regular_season_start", models.DateTimeField()),
                ("regular_season_end", models.DateTimeField()),
                ("playoff_start", models.DateTimeField()),
                ("playoff_end", models.DateTimeField()),
                ("current_match_day", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season",
                        to="public_leagues.publicleaguemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicMatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_day", models.IntegerField()),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("regular_season", "Regular Season"),
                            ("playoffs", "Playoffs"),
                        ],
                        default="regular_season",
                        max_length=20,
                    ),
                ),
                ("match_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_matches",
                        to="public_leagues.publicleaguemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_date"],
            },
        ),
        migrations.CreateModel(
            name="PublicMatchPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_a", models.IntegerField(default=0)),
                ("score_b", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="matches.publicmatchmodel",
                    ),
                ),
                (
                    "player_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_pairs_as_a",
                        to="users.userprofile",
                    ),
                ),
                (
                    "player_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_pairs_as_b",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicMatchScoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_scored", models.IntegerField(default=0)),
                ("bonus_points", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_scores",
                        to="matches.publicmatchmodel",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_match_scores",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_points"],
            },
        ),
        migrations.CreateModel(
            name="PublicPlayoffQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regular_season_rank", models.IntegerField()),
                ("total_points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playoff_qualifications",
                        to="public_leagues.publicleaguemodel",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["regular_season_rank"],
            },
        ),
        migrations.AddIndex(
            model_name="publicmatchmodel",
            index=models.Index(
                fields=["league_id", "match_type"],
                name="matches_pub_league__a10dff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicmatchmodel",
            index=models.Index(
                fields=["league_id", "status"], name="matches_pub_league__d22be9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicmatchpair",
            index=models.Index(
                fields=["match", "player_a"], name="matches_pub_match_i_0314a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicmatchpair",
            index=models.Index(
                fields=["match", "player_b"], name="matches_pub_match_i_bdeb91_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publicmatchscoremodel",
            unique_together={("match", "player")},
        ),
        migrations.AlterUniqueTogether(
            name="publicplayoffqualification",
            unique_together={("league", "player")},
        ),
    ]
